version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.2
    - 3.8.3
    - 3.9.1
  - dependency-name: cypress
    versions:
    - 6.2.1
    - 6.4.0
    - 6.5.0
    - 6.8.0
    - 7.0.1
    - 7.1.0
  - dependency-name: "@angular/cli"
    versions:
    - 11.1.2
    - 11.1.4
    - 11.2.0
    - 11.2.1
    - 11.2.2
    - 11.2.3
    - 11.2.5
    - 11.2.6
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
  - dependency-name: "@angular/language-service"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.2.0
    - 11.2.5
    - 11.2.6
  - dependency-name: typescript
    versions:
    - 3.9.7
  - dependency-name: jasmine-core
    versions:
    - 3.6.0
